server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/DemoDB"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
jwt:
  signerKey: "ce09726434bf05cb79a3200e2ed6511ac9729561fa3ae991d4cc09cc0b3454a3"